language: node_js
node_js:
  - "4.4.7"
install:
  - npm install -g elm
  - (cd tests && elm-package install -y)
script:
  - (cd tests && elm make src/Tests.elm --output tests.js && node -r ./scripts/workaround-elm-test-and-navigation tests.js)
